# Ejemplos

POST https://api-mongodb-dev-nnas.3.us-1.fl0.io/api/productos HTTP/1.1
content-type: application/json

{ 
    "nombre": "Jamon", 
    "precio": 60 
}

### 

POST https://api-mongodb-dev-nnas.3.us-1.fl0.io/api/productos HTTP/1.1
content-type: application/json

{ 
    "id": 3,
    "nombre": "Harina", 
    "precio": 2 
}


### 

GET https://api-mongodb-dev-nnas.3.us-1.fl0.io/api/productos HTTP/1.1
content-type: application/json

###

GET https://api-mongodb-dev-nnas.3.us-1.fl0.io/api/productos HTTP/1.1
content-type: application/json

###

PUT https://api-mongodb-dev-nnas.3.us-1.fl0.io/api/productos HTTP/1.1
content-type: application/json

{ 
    "id": 4,
    "nombre": "Cerveza", 
    "precio": 1.5 
}

###

DELETE https://api-mongodb-dev-nnas.3.us-1.fl0.io/api/productos HTTP/1.1
content-type: application/json

{
    "nombre": "Cerveza",
    "precio": 1.5
}

###

DELETE https://api-mongodb-dev-nnas.3.us-1.fl0.io/api/productos HTTP/1.1
content-type: application/json
